### ISSUE TITLE
segfault on gentoo

### ISSUE THREAD

**Issue by palica** [utsushi/utsushi#58]
Hi all!

I am having trouble starting utsushi on gentoo.

```
[I] media-gfx/utsushi [1]
     Installed versions:  9999(09:22:10 PM 06/02/2018)(gtk jpeg network nls openmp tiff udev -imagemagick)
     Homepage:            https://github.com/utsushi/utsushi
     Description:         SANE backend driver for newer Epson scanners (DS, ET, PX, etc)

```

The scanner gets detected, but utsushi fails.
```
utsushi list
esci:usb:/sys/devices/pci0000:00/0000:00:09.0/0000:03:00.0/usb9/9-4/9-4:1.0

scanimage -L                                                                                                                                                                          device `utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:09.0/0000:03:00.0/usb9/9-4/9-4:1.0' is a EPSON DS-1630
```

Pasting gdb output from run and backtrace:
```
gdb utsushi                                                                                                                                                                                           ✘ 139 
GNU gdb (Gentoo 8.1 p1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from utsushi...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/utsushi 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
process 18252 is executing new program: /bin/bash
process 18252 is executing new program: /usr/libexec/utsushi/utsushi-scan
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
process 18252 is executing new program: /bin/bash
process 18252 is executing new program: /usr/libexec/utsushi/utsushi-scan-gtkmm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffea40e700 (LWP 18256)]
[New Thread 0x7fffe9c0d700 (LWP 18257)]
[New Thread 0x7fffe8d85700 (LWP 18258)]

Thread 1 "utsushi-scan-gt" received signal SIGSEGV, Segmentation fault.
0x00007ffff6a87a23 in utsushi::descriptor::toggle_(bool, int) () from /usr/lib64/utsushi/libutsushi.so.0
(gdb) backtrace
#0  0x00007ffff6a87a23 in utsushi::descriptor::toggle_(bool, int) () from /usr/lib64/utsushi/libutsushi.so.0
#1  0x00007fffe8eb716c in utsushi::_drv_::esci::DS_16x0::configure() () from /usr/lib64/utsushi/libdrv-esci.so.0
#2  0x00007fffe8f7247f in libdrv_esci_LTX_scanner_factory () from /usr/lib64/utsushi/libdrv-esci.so.0
#3  0x00007ffff6a69760 in utsushi::scanner::create(utsushi::scanner::info const&) () from /usr/lib64/utsushi/libutsushi.so.0
#4  0x00007ffff7b33730 in utsushi::gtkmm::chooser::create_device(std::set<utsushi::scanner::info, std::less<utsushi::scanner::info>, std::allocator<utsushi::scanner::info> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/utsushi/libutsushi-gtkmm.so.0
#5  0x00007ffff7b32847 in utsushi::gtkmm::chooser::on_changed() () from /usr/lib64/utsushi/libutsushi-gtkmm.so.0
#6  0x00007ffff7702800 in Gtk::ComboBox_Class::changed_callback(_GtkComboBox*) () from /usr/lib64/libgtkmm-2.4.so.1
#7  0x00007ffff20cc276 in ?? () from /usr/lib64/libgobject-2.0.so.0
#8  0x00007ffff20e7721 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#9  0x00007ffff20e7c8f in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#10 0x00007ffff37c2971 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#11 0x00007ffff37c4e55 in gtk_combo_box_set_active () from /usr/lib64/libgtk-x11-2.0.so.0
#12 0x00007ffff7b3247f in utsushi::gtkmm::chooser::on_run() () from /usr/lib64/utsushi/libutsushi-gtkmm.so.0
#13 0x00007ffff7724501 in Gtk::RunSig::gtk_callback(void*) () from /usr/lib64/libgtkmm-2.4.so.1
#14 0x00007ffff3844c06 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#15 0x00007ffff7724a91 in Gtk::Main::run(Gtk::Window&) () from /usr/lib64/libgtkmm-2.4.so.1
#16 0x0000000000405b10 in ?? ()
#17 0x00007ffff56d98be in __libc_start_main () from /lib64/libc.so.6
#18 0x0000000000405f0a in ?? ()
(gdb) 
```

Please give me instructions as what to send next or how to narrow down the issue.Thank you.

**Comment by palica** [comment]
it works now with +imagemagick useflag enabled. So kind of related to this maybe? https://github.com/utsushi/utsushi/issues/42
